name: Lint

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Lint
      run: |
          GO111MODULE=off | go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
          
          golangci-lint run     
